#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("MinesweeperPlus.Resource", IsApplication=true)]

namespace MinesweeperPlus
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Xamarin.Essentials.Resource.Attribute.font = global::MinesweeperPlus.Resource.Attribute.font;
			global::Xamarin.Essentials.Resource.Attribute.fontProviderAuthority = global::MinesweeperPlus.Resource.Attribute.fontProviderAuthority;
			global::Xamarin.Essentials.Resource.Attribute.fontProviderCerts = global::MinesweeperPlus.Resource.Attribute.fontProviderCerts;
			global::Xamarin.Essentials.Resource.Attribute.fontProviderFetchStrategy = global::MinesweeperPlus.Resource.Attribute.fontProviderFetchStrategy;
			global::Xamarin.Essentials.Resource.Attribute.fontProviderFetchTimeout = global::MinesweeperPlus.Resource.Attribute.fontProviderFetchTimeout;
			global::Xamarin.Essentials.Resource.Attribute.fontProviderPackage = global::MinesweeperPlus.Resource.Attribute.fontProviderPackage;
			global::Xamarin.Essentials.Resource.Attribute.fontProviderQuery = global::MinesweeperPlus.Resource.Attribute.fontProviderQuery;
			global::Xamarin.Essentials.Resource.Attribute.fontStyle = global::MinesweeperPlus.Resource.Attribute.fontStyle;
			global::Xamarin.Essentials.Resource.Attribute.fontWeight = global::MinesweeperPlus.Resource.Attribute.fontWeight;
			global::Xamarin.Essentials.Resource.Boolean.abc_action_bar_embed_tabs = global::MinesweeperPlus.Resource.Boolean.abc_action_bar_embed_tabs;
			global::Xamarin.Essentials.Resource.Color.notification_action_color_filter = global::MinesweeperPlus.Resource.Color.notification_action_color_filter;
			global::Xamarin.Essentials.Resource.Color.notification_icon_bg_color = global::MinesweeperPlus.Resource.Color.notification_icon_bg_color;
			global::Xamarin.Essentials.Resource.Color.ripple_material_light = global::MinesweeperPlus.Resource.Color.ripple_material_light;
			global::Xamarin.Essentials.Resource.Color.secondary_text_default_material_light = global::MinesweeperPlus.Resource.Color.secondary_text_default_material_light;
			global::Xamarin.Essentials.Resource.Dimension.compat_button_inset_horizontal_material = global::MinesweeperPlus.Resource.Dimension.compat_button_inset_horizontal_material;
			global::Xamarin.Essentials.Resource.Dimension.compat_button_inset_vertical_material = global::MinesweeperPlus.Resource.Dimension.compat_button_inset_vertical_material;
			global::Xamarin.Essentials.Resource.Dimension.compat_button_padding_horizontal_material = global::MinesweeperPlus.Resource.Dimension.compat_button_padding_horizontal_material;
			global::Xamarin.Essentials.Resource.Dimension.compat_button_padding_vertical_material = global::MinesweeperPlus.Resource.Dimension.compat_button_padding_vertical_material;
			global::Xamarin.Essentials.Resource.Dimension.compat_control_corner_material = global::MinesweeperPlus.Resource.Dimension.compat_control_corner_material;
			global::Xamarin.Essentials.Resource.Dimension.notification_action_icon_size = global::MinesweeperPlus.Resource.Dimension.notification_action_icon_size;
			global::Xamarin.Essentials.Resource.Dimension.notification_action_text_size = global::MinesweeperPlus.Resource.Dimension.notification_action_text_size;
			global::Xamarin.Essentials.Resource.Dimension.notification_big_circle_margin = global::MinesweeperPlus.Resource.Dimension.notification_big_circle_margin;
			global::Xamarin.Essentials.Resource.Dimension.notification_content_margin_start = global::MinesweeperPlus.Resource.Dimension.notification_content_margin_start;
			global::Xamarin.Essentials.Resource.Dimension.notification_large_icon_height = global::MinesweeperPlus.Resource.Dimension.notification_large_icon_height;
			global::Xamarin.Essentials.Resource.Dimension.notification_large_icon_width = global::MinesweeperPlus.Resource.Dimension.notification_large_icon_width;
			global::Xamarin.Essentials.Resource.Dimension.notification_main_column_padding_top = global::MinesweeperPlus.Resource.Dimension.notification_main_column_padding_top;
			global::Xamarin.Essentials.Resource.Dimension.notification_media_narrow_margin = global::MinesweeperPlus.Resource.Dimension.notification_media_narrow_margin;
			global::Xamarin.Essentials.Resource.Dimension.notification_right_icon_size = global::MinesweeperPlus.Resource.Dimension.notification_right_icon_size;
			global::Xamarin.Essentials.Resource.Dimension.notification_right_side_padding_top = global::MinesweeperPlus.Resource.Dimension.notification_right_side_padding_top;
			global::Xamarin.Essentials.Resource.Dimension.notification_small_icon_background_padding = global::MinesweeperPlus.Resource.Dimension.notification_small_icon_background_padding;
			global::Xamarin.Essentials.Resource.Dimension.notification_small_icon_size_as_large = global::MinesweeperPlus.Resource.Dimension.notification_small_icon_size_as_large;
			global::Xamarin.Essentials.Resource.Dimension.notification_subtext_size = global::MinesweeperPlus.Resource.Dimension.notification_subtext_size;
			global::Xamarin.Essentials.Resource.Dimension.notification_top_pad = global::MinesweeperPlus.Resource.Dimension.notification_top_pad;
			global::Xamarin.Essentials.Resource.Dimension.notification_top_pad_large_text = global::MinesweeperPlus.Resource.Dimension.notification_top_pad_large_text;
			global::Xamarin.Essentials.Resource.Drawable.notification_action_background = global::MinesweeperPlus.Resource.Drawable.notification_action_background;
			global::Xamarin.Essentials.Resource.Drawable.notification_bg = global::MinesweeperPlus.Resource.Drawable.notification_bg;
			global::Xamarin.Essentials.Resource.Drawable.notification_bg_low = global::MinesweeperPlus.Resource.Drawable.notification_bg_low;
			global::Xamarin.Essentials.Resource.Drawable.notification_bg_low_normal = global::MinesweeperPlus.Resource.Drawable.notification_bg_low_normal;
			global::Xamarin.Essentials.Resource.Drawable.notification_bg_low_pressed = global::MinesweeperPlus.Resource.Drawable.notification_bg_low_pressed;
			global::Xamarin.Essentials.Resource.Drawable.notification_bg_normal = global::MinesweeperPlus.Resource.Drawable.notification_bg_normal;
			global::Xamarin.Essentials.Resource.Drawable.notification_bg_normal_pressed = global::MinesweeperPlus.Resource.Drawable.notification_bg_normal_pressed;
			global::Xamarin.Essentials.Resource.Drawable.notification_icon_background = global::MinesweeperPlus.Resource.Drawable.notification_icon_background;
			global::Xamarin.Essentials.Resource.Drawable.notification_template_icon_bg = global::MinesweeperPlus.Resource.Drawable.notification_template_icon_bg;
			global::Xamarin.Essentials.Resource.Drawable.notification_template_icon_low_bg = global::MinesweeperPlus.Resource.Drawable.notification_template_icon_low_bg;
			global::Xamarin.Essentials.Resource.Drawable.notification_tile_bg = global::MinesweeperPlus.Resource.Drawable.notification_tile_bg;
			global::Xamarin.Essentials.Resource.Drawable.notify_panel_notification_icon_bg = global::MinesweeperPlus.Resource.Drawable.notify_panel_notification_icon_bg;
			global::Xamarin.Essentials.Resource.Id.action_container = global::MinesweeperPlus.Resource.Id.action_container;
			global::Xamarin.Essentials.Resource.Id.action_divider = global::MinesweeperPlus.Resource.Id.action_divider;
			global::Xamarin.Essentials.Resource.Id.action_image = global::MinesweeperPlus.Resource.Id.action_image;
			global::Xamarin.Essentials.Resource.Id.action_text = global::MinesweeperPlus.Resource.Id.action_text;
			global::Xamarin.Essentials.Resource.Id.actions = global::MinesweeperPlus.Resource.Id.actions;
			global::Xamarin.Essentials.Resource.Id.async = global::MinesweeperPlus.Resource.Id.async;
			global::Xamarin.Essentials.Resource.Id.blocking = global::MinesweeperPlus.Resource.Id.blocking;
			global::Xamarin.Essentials.Resource.Id.chronometer = global::MinesweeperPlus.Resource.Id.chronometer;
			global::Xamarin.Essentials.Resource.Id.forever = global::MinesweeperPlus.Resource.Id.forever;
			global::Xamarin.Essentials.Resource.Id.icon = global::MinesweeperPlus.Resource.Id.icon;
			global::Xamarin.Essentials.Resource.Id.icon_group = global::MinesweeperPlus.Resource.Id.icon_group;
			global::Xamarin.Essentials.Resource.Id.info = global::MinesweeperPlus.Resource.Id.info;
			global::Xamarin.Essentials.Resource.Id.italic = global::MinesweeperPlus.Resource.Id.italic;
			global::Xamarin.Essentials.Resource.Id.line1 = global::MinesweeperPlus.Resource.Id.line1;
			global::Xamarin.Essentials.Resource.Id.line3 = global::MinesweeperPlus.Resource.Id.line3;
			global::Xamarin.Essentials.Resource.Id.normal = global::MinesweeperPlus.Resource.Id.normal;
			global::Xamarin.Essentials.Resource.Id.notification_background = global::MinesweeperPlus.Resource.Id.notification_background;
			global::Xamarin.Essentials.Resource.Id.notification_main_column = global::MinesweeperPlus.Resource.Id.notification_main_column;
			global::Xamarin.Essentials.Resource.Id.notification_main_column_container = global::MinesweeperPlus.Resource.Id.notification_main_column_container;
			global::Xamarin.Essentials.Resource.Id.right_icon = global::MinesweeperPlus.Resource.Id.right_icon;
			global::Xamarin.Essentials.Resource.Id.right_side = global::MinesweeperPlus.Resource.Id.right_side;
			global::Xamarin.Essentials.Resource.Id.tag_transition_group = global::MinesweeperPlus.Resource.Id.tag_transition_group;
			global::Xamarin.Essentials.Resource.Id.text = global::MinesweeperPlus.Resource.Id.text;
			global::Xamarin.Essentials.Resource.Id.text2 = global::MinesweeperPlus.Resource.Id.text2;
			global::Xamarin.Essentials.Resource.Id.time = global::MinesweeperPlus.Resource.Id.time;
			global::Xamarin.Essentials.Resource.Id.title = global::MinesweeperPlus.Resource.Id.title;
			global::Xamarin.Essentials.Resource.Integer.status_bar_notification_info_maxnum = global::MinesweeperPlus.Resource.Integer.status_bar_notification_info_maxnum;
			global::Xamarin.Essentials.Resource.Layout.notification_action = global::MinesweeperPlus.Resource.Layout.notification_action;
			global::Xamarin.Essentials.Resource.Layout.notification_action_tombstone = global::MinesweeperPlus.Resource.Layout.notification_action_tombstone;
			global::Xamarin.Essentials.Resource.Layout.notification_template_custom_big = global::MinesweeperPlus.Resource.Layout.notification_template_custom_big;
			global::Xamarin.Essentials.Resource.Layout.notification_template_icon_group = global::MinesweeperPlus.Resource.Layout.notification_template_icon_group;
			global::Xamarin.Essentials.Resource.Layout.notification_template_part_chronometer = global::MinesweeperPlus.Resource.Layout.notification_template_part_chronometer;
			global::Xamarin.Essentials.Resource.Layout.notification_template_part_time = global::MinesweeperPlus.Resource.Layout.notification_template_part_time;
			global::Xamarin.Essentials.Resource.String.status_bar_notification_info_overflow = global::MinesweeperPlus.Resource.String.status_bar_notification_info_overflow;
			global::Xamarin.Essentials.Resource.Style.TextAppearance_Compat_Notification = global::MinesweeperPlus.Resource.Style.TextAppearance_Compat_Notification;
			global::Xamarin.Essentials.Resource.Style.TextAppearance_Compat_Notification_Info = global::MinesweeperPlus.Resource.Style.TextAppearance_Compat_Notification_Info;
			global::Xamarin.Essentials.Resource.Style.TextAppearance_Compat_Notification_Line2 = global::MinesweeperPlus.Resource.Style.TextAppearance_Compat_Notification_Line2;
			global::Xamarin.Essentials.Resource.Style.TextAppearance_Compat_Notification_Time = global::MinesweeperPlus.Resource.Style.TextAppearance_Compat_Notification_Time;
			global::Xamarin.Essentials.Resource.Style.TextAppearance_Compat_Notification_Title = global::MinesweeperPlus.Resource.Style.TextAppearance_Compat_Notification_Title;
			global::Xamarin.Essentials.Resource.Style.Widget_Compat_NotificationActionContainer = global::MinesweeperPlus.Resource.Style.Widget_Compat_NotificationActionContainer;
			global::Xamarin.Essentials.Resource.Style.Widget_Compat_NotificationActionText = global::MinesweeperPlus.Resource.Style.Widget_Compat_NotificationActionText;
			global::Xamarin.Essentials.Resource.Styleable.FontFamily = global::MinesweeperPlus.Resource.Styleable.FontFamily;
			global::Xamarin.Essentials.Resource.Styleable.FontFamily_fontProviderAuthority = global::MinesweeperPlus.Resource.Styleable.FontFamily_fontProviderAuthority;
			global::Xamarin.Essentials.Resource.Styleable.FontFamily_fontProviderCerts = global::MinesweeperPlus.Resource.Styleable.FontFamily_fontProviderCerts;
			global::Xamarin.Essentials.Resource.Styleable.FontFamily_fontProviderFetchStrategy = global::MinesweeperPlus.Resource.Styleable.FontFamily_fontProviderFetchStrategy;
			global::Xamarin.Essentials.Resource.Styleable.FontFamily_fontProviderFetchTimeout = global::MinesweeperPlus.Resource.Styleable.FontFamily_fontProviderFetchTimeout;
			global::Xamarin.Essentials.Resource.Styleable.FontFamily_fontProviderPackage = global::MinesweeperPlus.Resource.Styleable.FontFamily_fontProviderPackage;
			global::Xamarin.Essentials.Resource.Styleable.FontFamily_fontProviderQuery = global::MinesweeperPlus.Resource.Styleable.FontFamily_fontProviderQuery;
			global::Xamarin.Essentials.Resource.Styleable.FontFamilyFont = global::MinesweeperPlus.Resource.Styleable.FontFamilyFont;
			global::Xamarin.Essentials.Resource.Styleable.FontFamilyFont_android_font = global::MinesweeperPlus.Resource.Styleable.FontFamilyFont_android_font;
			global::Xamarin.Essentials.Resource.Styleable.FontFamilyFont_android_fontStyle = global::MinesweeperPlus.Resource.Styleable.FontFamilyFont_android_fontStyle;
			global::Xamarin.Essentials.Resource.Styleable.FontFamilyFont_android_fontWeight = global::MinesweeperPlus.Resource.Styleable.FontFamilyFont_android_fontWeight;
			global::Xamarin.Essentials.Resource.Styleable.FontFamilyFont_font = global::MinesweeperPlus.Resource.Styleable.FontFamilyFont_font;
			global::Xamarin.Essentials.Resource.Styleable.FontFamilyFont_fontStyle = global::MinesweeperPlus.Resource.Styleable.FontFamilyFont_fontStyle;
			global::Xamarin.Essentials.Resource.Styleable.FontFamilyFont_fontWeight = global::MinesweeperPlus.Resource.Styleable.FontFamilyFont_fontWeight;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010007
			public const int font = 2130771975;
			
			// aapt resource value: 0x7f010000
			public const int fontProviderAuthority = 2130771968;
			
			// aapt resource value: 0x7f010003
			public const int fontProviderCerts = 2130771971;
			
			// aapt resource value: 0x7f010004
			public const int fontProviderFetchStrategy = 2130771972;
			
			// aapt resource value: 0x7f010005
			public const int fontProviderFetchTimeout = 2130771973;
			
			// aapt resource value: 0x7f010001
			public const int fontProviderPackage = 2130771969;
			
			// aapt resource value: 0x7f010002
			public const int fontProviderQuery = 2130771970;
			
			// aapt resource value: 0x7f010006
			public const int fontStyle = 2130771974;
			
			// aapt resource value: 0x7f010008
			public const int fontWeight = 2130771976;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Boolean
		{
			
			// aapt resource value: 0x7f060000
			public const int abc_action_bar_embed_tabs = 2131099648;
			
			static Boolean()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Boolean()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f080006
			public const int colorAccent = 2131230726;
			
			// aapt resource value: 0x7f080004
			public const int colorPrimary = 2131230724;
			
			// aapt resource value: 0x7f080005
			public const int colorPrimaryDark = 2131230725;
			
			// aapt resource value: 0x7f080007
			public const int ic_launcher_background = 2131230727;
			
			// aapt resource value: 0x7f080000
			public const int notification_action_color_filter = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int notification_icon_bg_color = 2131230721;
			
			// aapt resource value: 0x7f080002
			public const int ripple_material_light = 2131230722;
			
			// aapt resource value: 0x7f080003
			public const int secondary_text_default_material_light = 2131230723;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f070004
			public const int compat_button_inset_horizontal_material = 2131165188;
			
			// aapt resource value: 0x7f070005
			public const int compat_button_inset_vertical_material = 2131165189;
			
			// aapt resource value: 0x7f070006
			public const int compat_button_padding_horizontal_material = 2131165190;
			
			// aapt resource value: 0x7f070007
			public const int compat_button_padding_vertical_material = 2131165191;
			
			// aapt resource value: 0x7f070008
			public const int compat_control_corner_material = 2131165192;
			
			// aapt resource value: 0x7f070009
			public const int notification_action_icon_size = 2131165193;
			
			// aapt resource value: 0x7f07000a
			public const int notification_action_text_size = 2131165194;
			
			// aapt resource value: 0x7f07000b
			public const int notification_big_circle_margin = 2131165195;
			
			// aapt resource value: 0x7f070001
			public const int notification_content_margin_start = 2131165185;
			
			// aapt resource value: 0x7f07000c
			public const int notification_large_icon_height = 2131165196;
			
			// aapt resource value: 0x7f07000d
			public const int notification_large_icon_width = 2131165197;
			
			// aapt resource value: 0x7f070002
			public const int notification_main_column_padding_top = 2131165186;
			
			// aapt resource value: 0x7f070003
			public const int notification_media_narrow_margin = 2131165187;
			
			// aapt resource value: 0x7f07000e
			public const int notification_right_icon_size = 2131165198;
			
			// aapt resource value: 0x7f070000
			public const int notification_right_side_padding_top = 2131165184;
			
			// aapt resource value: 0x7f07000f
			public const int notification_small_icon_background_padding = 2131165199;
			
			// aapt resource value: 0x7f070010
			public const int notification_small_icon_size_as_large = 2131165200;
			
			// aapt resource value: 0x7f070011
			public const int notification_subtext_size = 2131165201;
			
			// aapt resource value: 0x7f070012
			public const int notification_top_pad = 2131165202;
			
			// aapt resource value: 0x7f070013
			public const int notification_top_pad_large_text = 2131165203;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int box_0 = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int box_bomb = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int box_bomb_red = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int box_dot_1 = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int box_dot_2 = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int box_dot_3 = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int box_dot_4 = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int box_dot_5 = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int box_dot_6 = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int box_dot_7 = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int box_dot_8 = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int box_flag = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int box_flag_green = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int box_flag_wrong = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int box_up = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int btn_cancel = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int btn_flag_to_target = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int btn_heart = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int btn_home = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int btn_homepage = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int btn_plus = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int btn_star_to_gift = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int btn_target_to_flag = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int deal_330 = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int diamond = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int emoji_crying = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int emoji_glasses = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int emoji_glasses_top = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int emoji_sad = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int emoji_smiling = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int emoji_surprised_red = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int emoji_surprised_yellow = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int flag = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int flag2 = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int flag_start = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int gift = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int info = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int like = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int notification_action_background = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int notification_bg = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int notification_bg_low = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int notification_bg_low_normal = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int notification_bg_low_pressed = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int notification_bg_normal = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int notification_bg_normal_pressed = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int notification_icon_background = 2130837549;
			
			// aapt resource value: 0x7f020047
			public const int notification_template_icon_bg = 2130837575;
			
			// aapt resource value: 0x7f020048
			public const int notification_template_icon_low_bg = 2130837576;
			
			// aapt resource value: 0x7f02002e
			public const int notification_tile_bg = 2130837550;
			
			// aapt resource value: 0x7f02002f
			public const int notify_panel_notification_icon_bg = 2130837551;
			
			// aapt resource value: 0x7f020030
			public const int rating = 2130837552;
			
			// aapt resource value: 0x7f020031
			public const int red_heart = 2130837553;
			
			// aapt resource value: 0x7f020032
			public const int red_plus = 2130837554;
			
			// aapt resource value: 0x7f020033
			public const int red_star = 2130837555;
			
			// aapt resource value: 0x7f020034
			public const int settings = 2130837556;
			
			// aapt resource value: 0x7f020035
			public const int settings2 = 2130837557;
			
			// aapt resource value: 0x7f020036
			public const int settings3 = 2130837558;
			
			// aapt resource value: 0x7f020037
			public const int seven_seg_0 = 2130837559;
			
			// aapt resource value: 0x7f020038
			public const int seven_seg_1 = 2130837560;
			
			// aapt resource value: 0x7f020039
			public const int seven_seg_2 = 2130837561;
			
			// aapt resource value: 0x7f02003a
			public const int seven_seg_3 = 2130837562;
			
			// aapt resource value: 0x7f02003b
			public const int seven_seg_4 = 2130837563;
			
			// aapt resource value: 0x7f02003c
			public const int seven_seg_5 = 2130837564;
			
			// aapt resource value: 0x7f02003d
			public const int seven_seg_6 = 2130837565;
			
			// aapt resource value: 0x7f02003e
			public const int seven_seg_7 = 2130837566;
			
			// aapt resource value: 0x7f02003f
			public const int seven_seg_8 = 2130837567;
			
			// aapt resource value: 0x7f020040
			public const int seven_seg_9 = 2130837568;
			
			// aapt resource value: 0x7f020041
			public const int seven_seg_column = 2130837569;
			
			// aapt resource value: 0x7f020042
			public const int seven_seg_minus = 2130837570;
			
			// aapt resource value: 0x7f020043
			public const int seven_seg_null = 2130837571;
			
			// aapt resource value: 0x7f020044
			public const int share = 2130837572;
			
			// aapt resource value: 0x7f020045
			public const int start_330 = 2130837573;
			
			// aapt resource value: 0x7f020046
			public const int thumbs_up_330 = 2130837574;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f0a003a
			public const int action_container = 2131361850;
			
			// aapt resource value: 0x7f0a0046
			public const int action_divider = 2131361862;
			
			// aapt resource value: 0x7f0a003b
			public const int action_image = 2131361851;
			
			// aapt resource value: 0x7f0a003c
			public const int action_text = 2131361852;
			
			// aapt resource value: 0x7f0a0047
			public const int actions = 2131361863;
			
			// aapt resource value: 0x7f0a0006
			public const int async = 2131361798;
			
			// aapt resource value: 0x7f0a0007
			public const int blocking = 2131361799;
			
			// aapt resource value: 0x7f0a0035
			public const int btnAppGift = 2131361845;
			
			// aapt resource value: 0x7f0a0039
			public const int btnAppInfo = 2131361849;
			
			// aapt resource value: 0x7f0a0036
			public const int btnAppLike = 2131361846;
			
			// aapt resource value: 0x7f0a0038
			public const int btnAppSettings = 2131361848;
			
			// aapt resource value: 0x7f0a0037
			public const int btnAppShare = 2131361847;
			
			// aapt resource value: 0x7f0a001f
			public const int btnDontUseHeart = 2131361823;
			
			// aapt resource value: 0x7f0a001b
			public const int btnHome = 2131361819;
			
			// aapt resource value: 0x7f0a001c
			public const int btnNewGame = 2131361820;
			
			// aapt resource value: 0x7f0a0019
			public const int btnPlus = 2131361817;
			
			// aapt resource value: 0x7f0a0015
			public const int btnRestartGame = 2131361813;
			
			// aapt resource value: 0x7f0a001d
			public const int btnStarToGift = 2131361821;
			
			// aapt resource value: 0x7f0a0018
			public const int btnStarToGift2 = 2131361816;
			
			// aapt resource value: 0x7f0a0034
			public const int btnStart = 2131361844;
			
			// aapt resource value: 0x7f0a0014
			public const int btnToggleFlagDefault = 2131361812;
			
			// aapt resource value: 0x7f0a0021
			public const int btnUseHeart = 2131361825;
			
			// aapt resource value: 0x7f0a0045
			public const int chronometer = 2131361861;
			
			// aapt resource value: 0x7f0a0030
			public const int dgtHeart0 = 2131361840;
			
			// aapt resource value: 0x7f0a0031
			public const int dgtHeart1 = 2131361841;
			
			// aapt resource value: 0x7f0a002c
			public const int dgtPlus0 = 2131361836;
			
			// aapt resource value: 0x7f0a002d
			public const int dgtPlus1 = 2131361837;
			
			// aapt resource value: 0x7f0a0028
			public const int dgtStar0 = 2131361832;
			
			// aapt resource value: 0x7f0a0029
			public const int dgtStar1 = 2131361833;
			
			// aapt resource value: 0x7f0a0008
			public const int forever = 2131361800;
			
			// aapt resource value: 0x7f0a0032
			public const int gridLayout = 2131361842;
			
			// aapt resource value: 0x7f0a003e
			public const int icon = 2131361854;
			
			// aapt resource value: 0x7f0a0048
			public const int icon_group = 2131361864;
			
			// aapt resource value: 0x7f0a002f
			public const int imgBonusHeart = 2131361839;
			
			// aapt resource value: 0x7f0a002b
			public const int imgBonusPlus = 2131361835;
			
			// aapt resource value: 0x7f0a0027
			public const int imgBonusStar = 2131361831;
			
			// aapt resource value: 0x7f0a0020
			public const int imgSurprised = 2131361824;
			
			// aapt resource value: 0x7f0a0041
			public const int info = 2131361857;
			
			// aapt resource value: 0x7f0a0033
			public const int initLayout = 2131361843;
			
			// aapt resource value: 0x7f0a0009
			public const int italic = 2131361801;
			
			// aapt resource value: 0x7f0a0000
			public const int line1 = 2131361792;
			
			// aapt resource value: 0x7f0a0001
			public const int line3 = 2131361793;
			
			// aapt resource value: 0x7f0a000f
			public const int linearLayout1 = 2131361807;
			
			// aapt resource value: 0x7f0a000c
			public const int linearLayout3 = 2131361804;
			
			// aapt resource value: 0x7f0a000e
			public const int linearLayout4 = 2131361806;
			
			// aapt resource value: 0x7f0a0013
			public const int linearLayoutButtons = 2131361811;
			
			// aapt resource value: 0x7f0a000b
			public const int linearLayoutMain = 2131361803;
			
			// aapt resource value: 0x7f0a001a
			public const int linearLayoutMessage = 2131361818;
			
			// aapt resource value: 0x7f0a001e
			public const int linearLayoutUseHeart = 2131361822;
			
			// aapt resource value: 0x7f0a000a
			public const int normal = 2131361802;
			
			// aapt resource value: 0x7f0a0043
			public const int notification_background = 2131361859;
			
			// aapt resource value: 0x7f0a003f
			public const int notification_main_column = 2131361855;
			
			// aapt resource value: 0x7f0a003d
			public const int notification_main_column_container = 2131361853;
			
			// aapt resource value: 0x7f0a000d
			public const int prgGameLevel = 2131361805;
			
			// aapt resource value: 0x7f0a002e
			public const int prgGoldenTimes = 2131361838;
			
			// aapt resource value: 0x7f0a002a
			public const int prgSilverTimes = 2131361834;
			
			// aapt resource value: 0x7f0a0012
			public const int remainFlagDigit1 = 2131361810;
			
			// aapt resource value: 0x7f0a0011
			public const int remainFlagDigit10 = 2131361809;
			
			// aapt resource value: 0x7f0a0010
			public const int remainFlagDigit100 = 2131361808;
			
			// aapt resource value: 0x7f0a0042
			public const int right_icon = 2131361858;
			
			// aapt resource value: 0x7f0a0040
			public const int right_side = 2131361856;
			
			// aapt resource value: 0x7f0a0016
			public const int space1 = 2131361814;
			
			// aapt resource value: 0x7f0a0002
			public const int tag_transition_group = 2131361794;
			
			// aapt resource value: 0x7f0a0003
			public const int text = 2131361795;
			
			// aapt resource value: 0x7f0a0004
			public const int text2 = 2131361796;
			
			// aapt resource value: 0x7f0a0044
			public const int time = 2131361860;
			
			// aapt resource value: 0x7f0a0024
			public const int timerDigit_col = 2131361828;
			
			// aapt resource value: 0x7f0a0022
			public const int timerDigit_h1 = 2131361826;
			
			// aapt resource value: 0x7f0a0023
			public const int timerDigit_h2 = 2131361827;
			
			// aapt resource value: 0x7f0a0025
			public const int timerDigit_m1 = 2131361829;
			
			// aapt resource value: 0x7f0a0026
			public const int timerDigit_m2 = 2131361830;
			
			// aapt resource value: 0x7f0a0005
			public const int title = 2131361797;
			
			// aapt resource value: 0x7f0a0017
			public const int txtTest = 2131361815;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f0b0000
			public const int status_bar_notification_info_maxnum = 2131427328;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int activity_main = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int notification_action = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int notification_action_tombstone = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int notification_template_custom_big = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int notification_template_icon_group = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int notification_template_part_chronometer = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int notification_template_part_time = 2130968582;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int ic_launcher = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int ic_launcher_foreground = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int ic_launcher_round = 2130903042;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050002
			public const int action_settings = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int app_name = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int status_bar_notification_info_overflow = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f090007
			public const int AppTheme = 2131296263;
			
			// aapt resource value: 0x7f090000
			public const int TextAppearance_Compat_Notification = 2131296256;
			
			// aapt resource value: 0x7f090001
			public const int TextAppearance_Compat_Notification_Info = 2131296257;
			
			// aapt resource value: 0x7f090006
			public const int TextAppearance_Compat_Notification_Line2 = 2131296262;
			
			// aapt resource value: 0x7f090002
			public const int TextAppearance_Compat_Notification_Time = 2131296258;
			
			// aapt resource value: 0x7f090003
			public const int TextAppearance_Compat_Notification_Title = 2131296259;
			
			// aapt resource value: 0x7f090004
			public const int Widget_Compat_NotificationActionContainer = 2131296260;
			
			// aapt resource value: 0x7f090005
			public const int Widget_Compat_NotificationActionText = 2131296261;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] FontFamily = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973};
			
			// aapt resource value: 0
			public const int FontFamily_fontProviderAuthority = 0;
			
			// aapt resource value: 3
			public const int FontFamily_fontProviderCerts = 3;
			
			// aapt resource value: 4
			public const int FontFamily_fontProviderFetchStrategy = 4;
			
			// aapt resource value: 5
			public const int FontFamily_fontProviderFetchTimeout = 5;
			
			// aapt resource value: 1
			public const int FontFamily_fontProviderPackage = 1;
			
			// aapt resource value: 2
			public const int FontFamily_fontProviderQuery = 2;
			
			public static int[] FontFamilyFont = new int[] {
					16844082,
					16844083,
					16844095,
					2130771974,
					2130771975,
					2130771976};
			
			// aapt resource value: 0
			public const int FontFamilyFont_android_font = 0;
			
			// aapt resource value: 2
			public const int FontFamilyFont_android_fontStyle = 2;
			
			// aapt resource value: 1
			public const int FontFamilyFont_android_fontWeight = 1;
			
			// aapt resource value: 4
			public const int FontFamilyFont_font = 4;
			
			// aapt resource value: 3
			public const int FontFamilyFont_fontStyle = 3;
			
			// aapt resource value: 5
			public const int FontFamilyFont_fontWeight = 5;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
