#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("MinesweeperPlus.Resource", IsApplication=true)]

namespace MinesweeperPlus
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Xamarin.Essentials.Resource.Attribute.font = global::MinesweeperPlus.Resource.Attribute.font;
			global::Xamarin.Essentials.Resource.Attribute.fontProviderAuthority = global::MinesweeperPlus.Resource.Attribute.fontProviderAuthority;
			global::Xamarin.Essentials.Resource.Attribute.fontProviderCerts = global::MinesweeperPlus.Resource.Attribute.fontProviderCerts;
			global::Xamarin.Essentials.Resource.Attribute.fontProviderFetchStrategy = global::MinesweeperPlus.Resource.Attribute.fontProviderFetchStrategy;
			global::Xamarin.Essentials.Resource.Attribute.fontProviderFetchTimeout = global::MinesweeperPlus.Resource.Attribute.fontProviderFetchTimeout;
			global::Xamarin.Essentials.Resource.Attribute.fontProviderPackage = global::MinesweeperPlus.Resource.Attribute.fontProviderPackage;
			global::Xamarin.Essentials.Resource.Attribute.fontProviderQuery = global::MinesweeperPlus.Resource.Attribute.fontProviderQuery;
			global::Xamarin.Essentials.Resource.Attribute.fontStyle = global::MinesweeperPlus.Resource.Attribute.fontStyle;
			global::Xamarin.Essentials.Resource.Attribute.fontWeight = global::MinesweeperPlus.Resource.Attribute.fontWeight;
			global::Xamarin.Essentials.Resource.Boolean.abc_action_bar_embed_tabs = global::MinesweeperPlus.Resource.Boolean.abc_action_bar_embed_tabs;
			global::Xamarin.Essentials.Resource.Color.notification_action_color_filter = global::MinesweeperPlus.Resource.Color.notification_action_color_filter;
			global::Xamarin.Essentials.Resource.Color.notification_icon_bg_color = global::MinesweeperPlus.Resource.Color.notification_icon_bg_color;
			global::Xamarin.Essentials.Resource.Color.ripple_material_light = global::MinesweeperPlus.Resource.Color.ripple_material_light;
			global::Xamarin.Essentials.Resource.Color.secondary_text_default_material_light = global::MinesweeperPlus.Resource.Color.secondary_text_default_material_light;
			global::Xamarin.Essentials.Resource.Dimension.compat_button_inset_horizontal_material = global::MinesweeperPlus.Resource.Dimension.compat_button_inset_horizontal_material;
			global::Xamarin.Essentials.Resource.Dimension.compat_button_inset_vertical_material = global::MinesweeperPlus.Resource.Dimension.compat_button_inset_vertical_material;
			global::Xamarin.Essentials.Resource.Dimension.compat_button_padding_horizontal_material = global::MinesweeperPlus.Resource.Dimension.compat_button_padding_horizontal_material;
			global::Xamarin.Essentials.Resource.Dimension.compat_button_padding_vertical_material = global::MinesweeperPlus.Resource.Dimension.compat_button_padding_vertical_material;
			global::Xamarin.Essentials.Resource.Dimension.compat_control_corner_material = global::MinesweeperPlus.Resource.Dimension.compat_control_corner_material;
			global::Xamarin.Essentials.Resource.Dimension.notification_action_icon_size = global::MinesweeperPlus.Resource.Dimension.notification_action_icon_size;
			global::Xamarin.Essentials.Resource.Dimension.notification_action_text_size = global::MinesweeperPlus.Resource.Dimension.notification_action_text_size;
			global::Xamarin.Essentials.Resource.Dimension.notification_big_circle_margin = global::MinesweeperPlus.Resource.Dimension.notification_big_circle_margin;
			global::Xamarin.Essentials.Resource.Dimension.notification_content_margin_start = global::MinesweeperPlus.Resource.Dimension.notification_content_margin_start;
			global::Xamarin.Essentials.Resource.Dimension.notification_large_icon_height = global::MinesweeperPlus.Resource.Dimension.notification_large_icon_height;
			global::Xamarin.Essentials.Resource.Dimension.notification_large_icon_width = global::MinesweeperPlus.Resource.Dimension.notification_large_icon_width;
			global::Xamarin.Essentials.Resource.Dimension.notification_main_column_padding_top = global::MinesweeperPlus.Resource.Dimension.notification_main_column_padding_top;
			global::Xamarin.Essentials.Resource.Dimension.notification_media_narrow_margin = global::MinesweeperPlus.Resource.Dimension.notification_media_narrow_margin;
			global::Xamarin.Essentials.Resource.Dimension.notification_right_icon_size = global::MinesweeperPlus.Resource.Dimension.notification_right_icon_size;
			global::Xamarin.Essentials.Resource.Dimension.notification_right_side_padding_top = global::MinesweeperPlus.Resource.Dimension.notification_right_side_padding_top;
			global::Xamarin.Essentials.Resource.Dimension.notification_small_icon_background_padding = global::MinesweeperPlus.Resource.Dimension.notification_small_icon_background_padding;
			global::Xamarin.Essentials.Resource.Dimension.notification_small_icon_size_as_large = global::MinesweeperPlus.Resource.Dimension.notification_small_icon_size_as_large;
			global::Xamarin.Essentials.Resource.Dimension.notification_subtext_size = global::MinesweeperPlus.Resource.Dimension.notification_subtext_size;
			global::Xamarin.Essentials.Resource.Dimension.notification_top_pad = global::MinesweeperPlus.Resource.Dimension.notification_top_pad;
			global::Xamarin.Essentials.Resource.Dimension.notification_top_pad_large_text = global::MinesweeperPlus.Resource.Dimension.notification_top_pad_large_text;
			global::Xamarin.Essentials.Resource.Drawable.notification_action_background = global::MinesweeperPlus.Resource.Drawable.notification_action_background;
			global::Xamarin.Essentials.Resource.Drawable.notification_bg = global::MinesweeperPlus.Resource.Drawable.notification_bg;
			global::Xamarin.Essentials.Resource.Drawable.notification_bg_low = global::MinesweeperPlus.Resource.Drawable.notification_bg_low;
			global::Xamarin.Essentials.Resource.Drawable.notification_bg_low_normal = global::MinesweeperPlus.Resource.Drawable.notification_bg_low_normal;
			global::Xamarin.Essentials.Resource.Drawable.notification_bg_low_pressed = global::MinesweeperPlus.Resource.Drawable.notification_bg_low_pressed;
			global::Xamarin.Essentials.Resource.Drawable.notification_bg_normal = global::MinesweeperPlus.Resource.Drawable.notification_bg_normal;
			global::Xamarin.Essentials.Resource.Drawable.notification_bg_normal_pressed = global::MinesweeperPlus.Resource.Drawable.notification_bg_normal_pressed;
			global::Xamarin.Essentials.Resource.Drawable.notification_icon_background = global::MinesweeperPlus.Resource.Drawable.notification_icon_background;
			global::Xamarin.Essentials.Resource.Drawable.notification_template_icon_bg = global::MinesweeperPlus.Resource.Drawable.notification_template_icon_bg;
			global::Xamarin.Essentials.Resource.Drawable.notification_template_icon_low_bg = global::MinesweeperPlus.Resource.Drawable.notification_template_icon_low_bg;
			global::Xamarin.Essentials.Resource.Drawable.notification_tile_bg = global::MinesweeperPlus.Resource.Drawable.notification_tile_bg;
			global::Xamarin.Essentials.Resource.Drawable.notify_panel_notification_icon_bg = global::MinesweeperPlus.Resource.Drawable.notify_panel_notification_icon_bg;
			global::Xamarin.Essentials.Resource.Id.action_container = global::MinesweeperPlus.Resource.Id.action_container;
			global::Xamarin.Essentials.Resource.Id.action_divider = global::MinesweeperPlus.Resource.Id.action_divider;
			global::Xamarin.Essentials.Resource.Id.action_image = global::MinesweeperPlus.Resource.Id.action_image;
			global::Xamarin.Essentials.Resource.Id.action_text = global::MinesweeperPlus.Resource.Id.action_text;
			global::Xamarin.Essentials.Resource.Id.actions = global::MinesweeperPlus.Resource.Id.actions;
			global::Xamarin.Essentials.Resource.Id.async = global::MinesweeperPlus.Resource.Id.async;
			global::Xamarin.Essentials.Resource.Id.blocking = global::MinesweeperPlus.Resource.Id.blocking;
			global::Xamarin.Essentials.Resource.Id.chronometer = global::MinesweeperPlus.Resource.Id.chronometer;
			global::Xamarin.Essentials.Resource.Id.forever = global::MinesweeperPlus.Resource.Id.forever;
			global::Xamarin.Essentials.Resource.Id.icon = global::MinesweeperPlus.Resource.Id.icon;
			global::Xamarin.Essentials.Resource.Id.icon_group = global::MinesweeperPlus.Resource.Id.icon_group;
			global::Xamarin.Essentials.Resource.Id.info = global::MinesweeperPlus.Resource.Id.info;
			global::Xamarin.Essentials.Resource.Id.italic = global::MinesweeperPlus.Resource.Id.italic;
			global::Xamarin.Essentials.Resource.Id.line1 = global::MinesweeperPlus.Resource.Id.line1;
			global::Xamarin.Essentials.Resource.Id.line3 = global::MinesweeperPlus.Resource.Id.line3;
			global::Xamarin.Essentials.Resource.Id.normal = global::MinesweeperPlus.Resource.Id.normal;
			global::Xamarin.Essentials.Resource.Id.notification_background = global::MinesweeperPlus.Resource.Id.notification_background;
			global::Xamarin.Essentials.Resource.Id.notification_main_column = global::MinesweeperPlus.Resource.Id.notification_main_column;
			global::Xamarin.Essentials.Resource.Id.notification_main_column_container = global::MinesweeperPlus.Resource.Id.notification_main_column_container;
			global::Xamarin.Essentials.Resource.Id.right_icon = global::MinesweeperPlus.Resource.Id.right_icon;
			global::Xamarin.Essentials.Resource.Id.right_side = global::MinesweeperPlus.Resource.Id.right_side;
			global::Xamarin.Essentials.Resource.Id.tag_transition_group = global::MinesweeperPlus.Resource.Id.tag_transition_group;
			global::Xamarin.Essentials.Resource.Id.text = global::MinesweeperPlus.Resource.Id.text;
			global::Xamarin.Essentials.Resource.Id.text2 = global::MinesweeperPlus.Resource.Id.text2;
			global::Xamarin.Essentials.Resource.Id.time = global::MinesweeperPlus.Resource.Id.time;
			global::Xamarin.Essentials.Resource.Id.title = global::MinesweeperPlus.Resource.Id.title;
			global::Xamarin.Essentials.Resource.Integer.status_bar_notification_info_maxnum = global::MinesweeperPlus.Resource.Integer.status_bar_notification_info_maxnum;
			global::Xamarin.Essentials.Resource.Layout.notification_action = global::MinesweeperPlus.Resource.Layout.notification_action;
			global::Xamarin.Essentials.Resource.Layout.notification_action_tombstone = global::MinesweeperPlus.Resource.Layout.notification_action_tombstone;
			global::Xamarin.Essentials.Resource.Layout.notification_template_custom_big = global::MinesweeperPlus.Resource.Layout.notification_template_custom_big;
			global::Xamarin.Essentials.Resource.Layout.notification_template_icon_group = global::MinesweeperPlus.Resource.Layout.notification_template_icon_group;
			global::Xamarin.Essentials.Resource.Layout.notification_template_part_chronometer = global::MinesweeperPlus.Resource.Layout.notification_template_part_chronometer;
			global::Xamarin.Essentials.Resource.Layout.notification_template_part_time = global::MinesweeperPlus.Resource.Layout.notification_template_part_time;
			global::Xamarin.Essentials.Resource.String.status_bar_notification_info_overflow = global::MinesweeperPlus.Resource.String.status_bar_notification_info_overflow;
			global::Xamarin.Essentials.Resource.Style.TextAppearance_Compat_Notification = global::MinesweeperPlus.Resource.Style.TextAppearance_Compat_Notification;
			global::Xamarin.Essentials.Resource.Style.TextAppearance_Compat_Notification_Info = global::MinesweeperPlus.Resource.Style.TextAppearance_Compat_Notification_Info;
			global::Xamarin.Essentials.Resource.Style.TextAppearance_Compat_Notification_Line2 = global::MinesweeperPlus.Resource.Style.TextAppearance_Compat_Notification_Line2;
			global::Xamarin.Essentials.Resource.Style.TextAppearance_Compat_Notification_Time = global::MinesweeperPlus.Resource.Style.TextAppearance_Compat_Notification_Time;
			global::Xamarin.Essentials.Resource.Style.TextAppearance_Compat_Notification_Title = global::MinesweeperPlus.Resource.Style.TextAppearance_Compat_Notification_Title;
			global::Xamarin.Essentials.Resource.Style.Widget_Compat_NotificationActionContainer = global::MinesweeperPlus.Resource.Style.Widget_Compat_NotificationActionContainer;
			global::Xamarin.Essentials.Resource.Style.Widget_Compat_NotificationActionText = global::MinesweeperPlus.Resource.Style.Widget_Compat_NotificationActionText;
			global::Xamarin.Essentials.Resource.Xml.xamarin_essentials_fileprovider_file_paths = global::MinesweeperPlus.Resource.Xml.xamarin_essentials_fileprovider_file_paths;
			global::Xamarin.Essentials.Resource.Styleable.FontFamily = global::MinesweeperPlus.Resource.Styleable.FontFamily;
			global::Xamarin.Essentials.Resource.Styleable.FontFamily_fontProviderAuthority = global::MinesweeperPlus.Resource.Styleable.FontFamily_fontProviderAuthority;
			global::Xamarin.Essentials.Resource.Styleable.FontFamily_fontProviderCerts = global::MinesweeperPlus.Resource.Styleable.FontFamily_fontProviderCerts;
			global::Xamarin.Essentials.Resource.Styleable.FontFamily_fontProviderFetchStrategy = global::MinesweeperPlus.Resource.Styleable.FontFamily_fontProviderFetchStrategy;
			global::Xamarin.Essentials.Resource.Styleable.FontFamily_fontProviderFetchTimeout = global::MinesweeperPlus.Resource.Styleable.FontFamily_fontProviderFetchTimeout;
			global::Xamarin.Essentials.Resource.Styleable.FontFamily_fontProviderPackage = global::MinesweeperPlus.Resource.Styleable.FontFamily_fontProviderPackage;
			global::Xamarin.Essentials.Resource.Styleable.FontFamily_fontProviderQuery = global::MinesweeperPlus.Resource.Styleable.FontFamily_fontProviderQuery;
			global::Xamarin.Essentials.Resource.Styleable.FontFamilyFont = global::MinesweeperPlus.Resource.Styleable.FontFamilyFont;
			global::Xamarin.Essentials.Resource.Styleable.FontFamilyFont_android_font = global::MinesweeperPlus.Resource.Styleable.FontFamilyFont_android_font;
			global::Xamarin.Essentials.Resource.Styleable.FontFamilyFont_android_fontStyle = global::MinesweeperPlus.Resource.Styleable.FontFamilyFont_android_fontStyle;
			global::Xamarin.Essentials.Resource.Styleable.FontFamilyFont_android_fontWeight = global::MinesweeperPlus.Resource.Styleable.FontFamilyFont_android_fontWeight;
			global::Xamarin.Essentials.Resource.Styleable.FontFamilyFont_font = global::MinesweeperPlus.Resource.Styleable.FontFamilyFont_font;
			global::Xamarin.Essentials.Resource.Styleable.FontFamilyFont_fontStyle = global::MinesweeperPlus.Resource.Styleable.FontFamilyFont_fontStyle;
			global::Xamarin.Essentials.Resource.Styleable.FontFamilyFont_fontWeight = global::MinesweeperPlus.Resource.Styleable.FontFamilyFont_fontWeight;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010007
			public const int font = 2130771975;
			
			// aapt resource value: 0x7f010000
			public const int fontProviderAuthority = 2130771968;
			
			// aapt resource value: 0x7f010003
			public const int fontProviderCerts = 2130771971;
			
			// aapt resource value: 0x7f010004
			public const int fontProviderFetchStrategy = 2130771972;
			
			// aapt resource value: 0x7f010005
			public const int fontProviderFetchTimeout = 2130771973;
			
			// aapt resource value: 0x7f010001
			public const int fontProviderPackage = 2130771969;
			
			// aapt resource value: 0x7f010002
			public const int fontProviderQuery = 2130771970;
			
			// aapt resource value: 0x7f010006
			public const int fontStyle = 2130771974;
			
			// aapt resource value: 0x7f010008
			public const int fontWeight = 2130771976;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Boolean
		{
			
			// aapt resource value: 0x7f070000
			public const int abc_action_bar_embed_tabs = 2131165184;
			
			static Boolean()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Boolean()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f090006
			public const int colorAccent = 2131296262;
			
			// aapt resource value: 0x7f090004
			public const int colorPrimary = 2131296260;
			
			// aapt resource value: 0x7f090005
			public const int colorPrimaryDark = 2131296261;
			
			// aapt resource value: 0x7f090007
			public const int ic_launcher_background = 2131296263;
			
			// aapt resource value: 0x7f090000
			public const int notification_action_color_filter = 2131296256;
			
			// aapt resource value: 0x7f090001
			public const int notification_icon_bg_color = 2131296257;
			
			// aapt resource value: 0x7f090002
			public const int ripple_material_light = 2131296258;
			
			// aapt resource value: 0x7f090003
			public const int secondary_text_default_material_light = 2131296259;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f080004
			public const int compat_button_inset_horizontal_material = 2131230724;
			
			// aapt resource value: 0x7f080005
			public const int compat_button_inset_vertical_material = 2131230725;
			
			// aapt resource value: 0x7f080006
			public const int compat_button_padding_horizontal_material = 2131230726;
			
			// aapt resource value: 0x7f080007
			public const int compat_button_padding_vertical_material = 2131230727;
			
			// aapt resource value: 0x7f080008
			public const int compat_control_corner_material = 2131230728;
			
			// aapt resource value: 0x7f080009
			public const int notification_action_icon_size = 2131230729;
			
			// aapt resource value: 0x7f08000a
			public const int notification_action_text_size = 2131230730;
			
			// aapt resource value: 0x7f08000b
			public const int notification_big_circle_margin = 2131230731;
			
			// aapt resource value: 0x7f080001
			public const int notification_content_margin_start = 2131230721;
			
			// aapt resource value: 0x7f08000c
			public const int notification_large_icon_height = 2131230732;
			
			// aapt resource value: 0x7f08000d
			public const int notification_large_icon_width = 2131230733;
			
			// aapt resource value: 0x7f080002
			public const int notification_main_column_padding_top = 2131230722;
			
			// aapt resource value: 0x7f080003
			public const int notification_media_narrow_margin = 2131230723;
			
			// aapt resource value: 0x7f08000e
			public const int notification_right_icon_size = 2131230734;
			
			// aapt resource value: 0x7f080000
			public const int notification_right_side_padding_top = 2131230720;
			
			// aapt resource value: 0x7f08000f
			public const int notification_small_icon_background_padding = 2131230735;
			
			// aapt resource value: 0x7f080010
			public const int notification_small_icon_size_as_large = 2131230736;
			
			// aapt resource value: 0x7f080011
			public const int notification_subtext_size = 2131230737;
			
			// aapt resource value: 0x7f080012
			public const int notification_top_pad = 2131230738;
			
			// aapt resource value: 0x7f080013
			public const int notification_top_pad_large_text = 2131230739;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int box_0 = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int box_bomb = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int box_bomb_red = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int box_dot_1 = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int box_dot_2 = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int box_dot_3 = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int box_dot_4 = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int box_dot_5 = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int box_dot_6 = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int box_dot_7 = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int box_dot_8 = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int box_flag = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int box_flag_green = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int box_flag_wrong = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int box_up = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int btn_cancel = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int btn_flag_to_target = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int btn_heart = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int btn_home = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int btn_plus = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int btn_star_to_gift = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int btn_target_to_flag = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int deal_330 = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int emoji_crying = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int emoji_glasses = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int emoji_glasses_top = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int emoji_sad = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int emoji_smiling = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int emoji_surprised_red = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int emoji_surprised_yellow = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int notification_action_background = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int notification_bg = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int notification_bg_low = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int notification_bg_low_normal = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int notification_bg_low_pressed = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int notification_bg_normal = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int notification_bg_normal_pressed = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int notification_icon_background = 2130837541;
			
			// aapt resource value: 0x7f02003a
			public const int notification_template_icon_bg = 2130837562;
			
			// aapt resource value: 0x7f02003b
			public const int notification_template_icon_low_bg = 2130837563;
			
			// aapt resource value: 0x7f020026
			public const int notification_tile_bg = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int notify_panel_notification_icon_bg = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int red_heart = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int red_plus = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int red_star = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int seven_seg_0 = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int seven_seg_1 = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int seven_seg_2 = 2130837549;
			
			// aapt resource value: 0x7f02002e
			public const int seven_seg_3 = 2130837550;
			
			// aapt resource value: 0x7f02002f
			public const int seven_seg_4 = 2130837551;
			
			// aapt resource value: 0x7f020030
			public const int seven_seg_5 = 2130837552;
			
			// aapt resource value: 0x7f020031
			public const int seven_seg_6 = 2130837553;
			
			// aapt resource value: 0x7f020032
			public const int seven_seg_7 = 2130837554;
			
			// aapt resource value: 0x7f020033
			public const int seven_seg_8 = 2130837555;
			
			// aapt resource value: 0x7f020034
			public const int seven_seg_9 = 2130837556;
			
			// aapt resource value: 0x7f020035
			public const int seven_seg_column = 2130837557;
			
			// aapt resource value: 0x7f020036
			public const int seven_seg_minus = 2130837558;
			
			// aapt resource value: 0x7f020037
			public const int seven_seg_null = 2130837559;
			
			// aapt resource value: 0x7f020038
			public const int start_330 = 2130837560;
			
			// aapt resource value: 0x7f020039
			public const int thumbs_up_330 = 2130837561;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f0b0035
			public const int action_container = 2131427381;
			
			// aapt resource value: 0x7f0b0041
			public const int action_divider = 2131427393;
			
			// aapt resource value: 0x7f0b0036
			public const int action_image = 2131427382;
			
			// aapt resource value: 0x7f0b0037
			public const int action_text = 2131427383;
			
			// aapt resource value: 0x7f0b0042
			public const int actions = 2131427394;
			
			// aapt resource value: 0x7f0b0006
			public const int async = 2131427334;
			
			// aapt resource value: 0x7f0b0007
			public const int blocking = 2131427335;
			
			// aapt resource value: 0x7f0b0034
			public const int btnAppDonate = 2131427380;
			
			// aapt resource value: 0x7f0b0033
			public const int btnAppLike = 2131427379;
			
			// aapt resource value: 0x7f0b001d
			public const int btnDontUseHeart = 2131427357;
			
			// aapt resource value: 0x7f0b0019
			public const int btnHome = 2131427353;
			
			// aapt resource value: 0x7f0b001a
			public const int btnNewGame = 2131427354;
			
			// aapt resource value: 0x7f0b0017
			public const int btnPlus = 2131427351;
			
			// aapt resource value: 0x7f0b0015
			public const int btnRestartGame = 2131427349;
			
			// aapt resource value: 0x7f0b001b
			public const int btnStarToGift = 2131427355;
			
			// aapt resource value: 0x7f0b0032
			public const int btnStart = 2131427378;
			
			// aapt resource value: 0x7f0b0014
			public const int btnToggleFlagDefault = 2131427348;
			
			// aapt resource value: 0x7f0b001f
			public const int btnUseHeart = 2131427359;
			
			// aapt resource value: 0x7f0b0040
			public const int chronometer = 2131427392;
			
			// aapt resource value: 0x7f0b002e
			public const int dgtHeart0 = 2131427374;
			
			// aapt resource value: 0x7f0b002f
			public const int dgtHeart1 = 2131427375;
			
			// aapt resource value: 0x7f0b002a
			public const int dgtPlus0 = 2131427370;
			
			// aapt resource value: 0x7f0b002b
			public const int dgtPlus1 = 2131427371;
			
			// aapt resource value: 0x7f0b0026
			public const int dgtStar0 = 2131427366;
			
			// aapt resource value: 0x7f0b0027
			public const int dgtStar1 = 2131427367;
			
			// aapt resource value: 0x7f0b0008
			public const int forever = 2131427336;
			
			// aapt resource value: 0x7f0b0030
			public const int gridLayout = 2131427376;
			
			// aapt resource value: 0x7f0b0039
			public const int icon = 2131427385;
			
			// aapt resource value: 0x7f0b0043
			public const int icon_group = 2131427395;
			
			// aapt resource value: 0x7f0b002d
			public const int imgBonusHeart = 2131427373;
			
			// aapt resource value: 0x7f0b0029
			public const int imgBonusPlus = 2131427369;
			
			// aapt resource value: 0x7f0b0025
			public const int imgBonusStar = 2131427365;
			
			// aapt resource value: 0x7f0b001e
			public const int imgSurprised = 2131427358;
			
			// aapt resource value: 0x7f0b003c
			public const int info = 2131427388;
			
			// aapt resource value: 0x7f0b0031
			public const int initLayout = 2131427377;
			
			// aapt resource value: 0x7f0b0009
			public const int italic = 2131427337;
			
			// aapt resource value: 0x7f0b0000
			public const int line1 = 2131427328;
			
			// aapt resource value: 0x7f0b0001
			public const int line3 = 2131427329;
			
			// aapt resource value: 0x7f0b000f
			public const int linearLayout1 = 2131427343;
			
			// aapt resource value: 0x7f0b000c
			public const int linearLayout3 = 2131427340;
			
			// aapt resource value: 0x7f0b000e
			public const int linearLayout4 = 2131427342;
			
			// aapt resource value: 0x7f0b0013
			public const int linearLayoutButtons = 2131427347;
			
			// aapt resource value: 0x7f0b000b
			public const int linearLayoutMain = 2131427339;
			
			// aapt resource value: 0x7f0b0018
			public const int linearLayoutMessage = 2131427352;
			
			// aapt resource value: 0x7f0b001c
			public const int linearLayoutUseHeart = 2131427356;
			
			// aapt resource value: 0x7f0b000a
			public const int normal = 2131427338;
			
			// aapt resource value: 0x7f0b003e
			public const int notification_background = 2131427390;
			
			// aapt resource value: 0x7f0b003a
			public const int notification_main_column = 2131427386;
			
			// aapt resource value: 0x7f0b0038
			public const int notification_main_column_container = 2131427384;
			
			// aapt resource value: 0x7f0b000d
			public const int prgGameLevel = 2131427341;
			
			// aapt resource value: 0x7f0b002c
			public const int prgGoldenTimes = 2131427372;
			
			// aapt resource value: 0x7f0b0028
			public const int prgSilverTimes = 2131427368;
			
			// aapt resource value: 0x7f0b0012
			public const int remainFlagDigit1 = 2131427346;
			
			// aapt resource value: 0x7f0b0011
			public const int remainFlagDigit10 = 2131427345;
			
			// aapt resource value: 0x7f0b0010
			public const int remainFlagDigit100 = 2131427344;
			
			// aapt resource value: 0x7f0b003d
			public const int right_icon = 2131427389;
			
			// aapt resource value: 0x7f0b003b
			public const int right_side = 2131427387;
			
			// aapt resource value: 0x7f0b0016
			public const int space1 = 2131427350;
			
			// aapt resource value: 0x7f0b0002
			public const int tag_transition_group = 2131427330;
			
			// aapt resource value: 0x7f0b0003
			public const int text = 2131427331;
			
			// aapt resource value: 0x7f0b0004
			public const int text2 = 2131427332;
			
			// aapt resource value: 0x7f0b003f
			public const int time = 2131427391;
			
			// aapt resource value: 0x7f0b0022
			public const int timerDigit_col = 2131427362;
			
			// aapt resource value: 0x7f0b0020
			public const int timerDigit_h1 = 2131427360;
			
			// aapt resource value: 0x7f0b0021
			public const int timerDigit_h2 = 2131427361;
			
			// aapt resource value: 0x7f0b0023
			public const int timerDigit_m1 = 2131427363;
			
			// aapt resource value: 0x7f0b0024
			public const int timerDigit_m2 = 2131427364;
			
			// aapt resource value: 0x7f0b0005
			public const int title = 2131427333;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f0c0000
			public const int status_bar_notification_info_maxnum = 2131492864;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int activity_main = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int notification_action = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int notification_action_tombstone = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int notification_template_custom_big = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int notification_template_icon_group = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int notification_template_part_chronometer = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int notification_template_part_time = 2130968582;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int ic_launcher = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int ic_launcher_foreground = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int ic_launcher_round = 2130903042;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060002
			public const int action_settings = 2131099650;
			
			// aapt resource value: 0x7f060001
			public const int app_name = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int status_bar_notification_info_overflow = 2131099648;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f0a0007
			public const int AppTheme = 2131361799;
			
			// aapt resource value: 0x7f0a0000
			public const int TextAppearance_Compat_Notification = 2131361792;
			
			// aapt resource value: 0x7f0a0001
			public const int TextAppearance_Compat_Notification_Info = 2131361793;
			
			// aapt resource value: 0x7f0a0006
			public const int TextAppearance_Compat_Notification_Line2 = 2131361798;
			
			// aapt resource value: 0x7f0a0002
			public const int TextAppearance_Compat_Notification_Time = 2131361794;
			
			// aapt resource value: 0x7f0a0003
			public const int TextAppearance_Compat_Notification_Title = 2131361795;
			
			// aapt resource value: 0x7f0a0004
			public const int Widget_Compat_NotificationActionContainer = 2131361796;
			
			// aapt resource value: 0x7f0a0005
			public const int Widget_Compat_NotificationActionText = 2131361797;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Xml
		{
			
			// aapt resource value: 0x7f050000
			public const int xamarin_essentials_fileprovider_file_paths = 2131034112;
			
			static Xml()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Xml()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] FontFamily = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973};
			
			// aapt resource value: 0
			public const int FontFamily_fontProviderAuthority = 0;
			
			// aapt resource value: 3
			public const int FontFamily_fontProviderCerts = 3;
			
			// aapt resource value: 4
			public const int FontFamily_fontProviderFetchStrategy = 4;
			
			// aapt resource value: 5
			public const int FontFamily_fontProviderFetchTimeout = 5;
			
			// aapt resource value: 1
			public const int FontFamily_fontProviderPackage = 1;
			
			// aapt resource value: 2
			public const int FontFamily_fontProviderQuery = 2;
			
			public static int[] FontFamilyFont = new int[] {
					16844082,
					16844083,
					16844095,
					2130771974,
					2130771975,
					2130771976};
			
			// aapt resource value: 0
			public const int FontFamilyFont_android_font = 0;
			
			// aapt resource value: 2
			public const int FontFamilyFont_android_fontStyle = 2;
			
			// aapt resource value: 1
			public const int FontFamilyFont_android_fontWeight = 1;
			
			// aapt resource value: 4
			public const int FontFamilyFont_font = 4;
			
			// aapt resource value: 3
			public const int FontFamilyFont_fontStyle = 3;
			
			// aapt resource value: 5
			public const int FontFamilyFont_fontWeight = 5;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
